"""add order id to support cases

Revision ID: d3a5564f3980
Revises: 5ab6e544afbd
Create Date: 2026-10-05 20:49:38.936247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a5564f3980'
down_revision: Union[str, Sequence[str], None] = '5ab6e544afbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_cases', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_support_cases_order_id'), 'support_cases', ['order_id'], unique=False)
    op.create_foreign_key(None, 'support_cases', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'support_cases', type_='foreignkey')
    op.drop_index(op.f('ix_support_cases_order_id'), table_name='support_cases')
    op.drop_column('support_cases', 'order_id')
    # ### end Alembic commands ###
